### ISSUE TITLE
システム名の決定

### ISSUE THREAD

**Issue by trkoh** [terakawakohei/MakuranoSousi#4]
[第二週演習課題](http://ws.cs.kobe-u.ac.jp/~masa-n/lecture/tokuronI/week2/work2.html)のタスク5中に，

-  チームリーダーは，チーム共有のGitHubレポジトリに，システム名を名前とする新しいフォルダを作成せよ．

とあります．皆で案を出して決めましょう！

暫定でproject-nameというフォルダを作成したので，決まり次第リネームするという形で

**Comment by trkoh** [comment]
- SharedTimer
    - 直訳．捻りなし

**Comment by MakotoOhashi** [comment]
・Punctual Please
  この名前では機能がわかりにくいか

**Comment by takegami-r** [comment]
Our Timer
寺川君のでいいと思ってる

**Comment by trkoh** [comment]
@youyoushirokunariyukuyamagiwa リーダー何か意見して～～

**Comment by youyoushirokunariyukuyamagiwa** [comment]
気づかずすみません。
shared timer でいいんじゃないかな。
わかりやすいしそこが特徴やし

**Comment by trkoh** [comment]
じゃあSharedTimerということにしましょう～皆さんありがとうございます
変更します！
