### ISSUE TITLE
議事録の共有・管理方法について

### ISSUE THREAD

**Issue by trkoh** [terakawakohei/MakuranoSousi#6]
毎週の議論内容とかをgitで管理するのはどうでしょうか？

例えば，/MakuranoSousi以下にminutesフォルダを作って，その中にマークダウン形式でどんどん入れてくイメージで

個人のgoogleドキュメントとかで管理するのもありですが，どうせならコードと一緒に一括管理したいような気持ちもあります

@MakotoOhashi 書記係さんが良ければ検討してみてください！

**Comment by MakotoOhashi** [comment]
確かにそうですね！
次回までにやっておきます！
